apiVersion: v1
kind: Secret
metadata:
  name: garmin-sync-secrets
  namespace: garmin
type: Opaque
stringData:
  GARMIN_EMAIL: "you@example.com"
  GARMIN_PASSWORD: "changeme"
  POSTGRES_HOST: "postgres.mercadona.svc.cluster.local"
  POSTGRES_PORT: "5432"
  POSTGRES_DB: "garmin"
  POSTGRES_USER: "garmin"
  POSTGRES_PASSWORD: "changeme"
